name: Build Bread Compact

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: "Select Bread Compact build"
        required: true
        default: all
        type: choice
        options:
          - all
          - bread-compact-esp32
          - bread-compact-esp32-128x32
          - bread-compact-esp32-lcd
          - bread-compact-ml307
          - bread-compact-ml307-128x64
          - bread-compact-nt26
          - bread-compact-wifi
          - bread-compact-wifi-128x64

permissions:
  contents: read

jobs:
  prepare:
    name: Determine variants to build
    runs-on: ubuntu-latest

    outputs:
      variants: ${{ steps.select.outputs.variants }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - id: list
        name: Get all variants
        run: |
          echo "all_variants=$(python scripts/release.py --list-boards --json)" >> $GITHUB_OUTPUT

      - id: select
        name: Select variants
        env:
          ALL_VARIANTS: ${{ steps.list.outputs.all_variants }}
          BUILD_TARGET: ${{ github.event.inputs.build_target }}
        run: |
          echo "Selected target: $BUILD_TARGET"

          if [ "$BUILD_TARGET" = "all" ]; then
            FILTERED=$(echo "$ALL_VARIANTS" | jq -c '
              map(
                select(
                  .full_name | startswith("bread-compact-")
                )
              )
            ')
          else
            FILTERED=$(echo "$ALL_VARIANTS" | jq -c \
              --arg target "$BUILD_TARGET" '
              map(
                select(
                  .full_name == $target
                )
              )
            ')
          fi

          echo "Selected variants:"
          echo "$FILTERED" | jq .

          echo "variants=$FILTERED" >> $GITHUB_OUTPUT

  build:
    name: Build ${{ matrix.full_name }}

    needs: prepare

    if: ${{ needs.prepare.outputs.variants != '[]' }}

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.variants) }}

    runs-on: ubuntu-latest

    container:
      image: espressif/idf:v5.5.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build current variant
        shell: bash
        run: |
          source $IDF_PATH/export.sh

          python scripts/release.py \
            "${{ matrix.board }}" \
            --name "${{ matrix.name }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xiaozhi_${{ matrix.full_name }}_${{ github.sha }}
          path: build/merged-binary.bin
          if-no-files-found: error
